# Generated by Django 2.2.5 on 2020-01-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('rest_data', models.CharField(max_length=100)),
                ('parking_info', models.CharField(max_length=100)),
                ('imp_path', models.CharField(max_length=225)),
            ],
        ),
    ]
