# Generated by Django 2.2.5 on 2020-01-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='shop1',
        ),
    ]
